import 'package:freezed_annotation/freezed_annotation.dart';

part 'financial_insight.freezed.dart';
part 'financial_insight.g.dart';

/// Types of financial insights that can be generated
enum InsightType {
  spending,    // Insights about spending patterns
  saving,      // Savings recommendations
  budget,      // Budget-related advice
  goal,        // Goal achievement insights
  anomaly,     // Unusual spending detection
  achievement, // Financial milestones reached
}

/// Priority levels for insights
enum InsightPriority {
  high,   // Urgent attention needed
  medium, // Should be reviewed soon
  low,    // Informational only
}

/// Entity representing a financial insight generated by AI
///
/// These insights help users understand their financial behavior
/// and make better decisions
@freezed
class FinancialInsight with _$FinancialInsight {
  const factory FinancialInsight({
    required String id,
    required String title,
    required String description,
    required InsightType type,
    required InsightPriority priority,
    required DateTime generatedAt,
    String? actionLink,
  }) = _FinancialInsight;

  factory FinancialInsight.fromJson(Map<String, dynamic> json) =>
      _$FinancialInsightFromJson(json);
}
