// Run: flutterfire configure
// to regenerate this file for your Firebase project
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJrtifyChFeScZ8OVT03gMgGfQpcdRASA',
    appId: '1:696790419250:android:ee16197fe352f18753b92b',
    messagingSenderId: '696790419250',
    projectId: 'finance-manager-ef55d',
    storageBucket: 'finance-manager-ef55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOldqhfzsQNL_ZsVARngTv93jTKYTrajI',
    appId: '1:696790419250:ios:270ac77c5a4b78f453b92b',
    messagingSenderId: '696790419250',
    projectId: 'finance-manager-ef55d',
    storageBucket: 'finance-manager-ef55d.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0f_btK7k6UNKqXAE7mO7IDBzFKMRSls',
    appId: '1:696790419250:web:45b1cd36958652d953b92b',
    messagingSenderId: '696790419250',
    projectId: 'finance-manager-ef55d',
    authDomain: 'finance-manager-ef55d.firebaseapp.com',
    storageBucket: 'finance-manager-ef55d.firebasestorage.app',
    measurementId: 'G-BXY8HBCJKD',
  );

}